gdp_by_cbsa <- read.csv("Final Database tables/gdp_by_cbsa.csv")
gdp_total_current_dollar_value <- read.csv("Final Database tables/gdp_total_current_dollar_value.csv")
geofips <- read.csv("Final Database tables/geofips.csv")
population <- read.csv("Final Database tables/population .csv")
population_top50 <- read.csv("Final Database tables/population_top50.csv")

pop_with_diff <- read.csv("Final Database tables/pop_with_diff.csv")
gdp_with_diff <- read.csv("Final Database tables/gdp_with_diff.csv")
pop_with_diff_top10 <- read.csv("Final Database tables/pop_with_diff_top10.csv")
gdp_pop_top50_long <- read.csv("Final Database tables/gdp_pop_top50_long.csv")
gdp_pop_with_diff <- read.csv("Final Database tables/gdp_pop_with_diff.csv")
medium_city_diff <- read.csv("Final Database tables/medium_city_diff.csv")
gdp_top20_under1mil <- read.csv("Final Database tables/gdp_top20_under1mil.csv")
pop_top20_under1mil <- read.csv("Final Database tables/pop_top20_under1mil.csv")
gdp_bot20_under1mil <- read.csv("Final Database tables/gdp_bot20_under1mil.csv")
pop_bot20_under1mil <- read.csv("Final Database tables/pop_bot20_under1mil.csv")
gdp_pop_diff <- read.csv("Final Database tables/gdp_pop_with_diff.csv")
large_city <- read.csv("Final Database tables/large_city.csv")
gdp_pop_final <- read.csv("Final Database tables/gdp_pop_final.csv")
land_mass <- read.csv("Final Database tables/land_mass.csv")
top50_gdp <- read.csv("Final Database tables/top50_gdp.csv")
top20_gdp <- read.csv("Final Database tables/top20_gdp.csv")
top10_gdp <- read.csv("Final Database tables/top10_gdp.csv")
gdp_by_cbsa_updated <- read.csv("Final Database Tables/gdp_by_cbsa_updated.csv")
pop_2024_final <- read.csv("Final Database Tables/pop_2024_final.csv")

view(gdp_with_diff)
view(gdp_pop_with_diff)
view(pop_with_diff_top10)
view(gdp_pop_top50_long)
view(pop_top20_under1mil)

view(gdp_pop_final)
view(land_mass)


write.csv(gdp_pop_land_mass, "~/Documents/gdp_pop_land_mass.csv", row.names = FALSE)
