install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("DBI")
install.packages("RMySQL")
install.packages("ggforce")
install.packages("rmdformats")
install.packages("kableExtra")


library(tidyverse)
library(dplyr)
library(tidyr)
library(DBI)
library(RMySQL)
library(ggforce)
library(scales)
library(rmdformats)
library(purrr)
library(broom)
library(knitr)
library(MASS)
library(magrittr)
library(kableExtra)
